# See https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:

  - package-ecosystem: "gomod"
    open-pull-requests-limit: 2
    directory: "/hack/update-go-mod"
    schedule:
      interval: "daily"

# Our own CI job is responsible for updating this go.mod file now.
#  - package-ecosystem: "gomod"
#    open-pull-requests-limit: 100
#    directory: "/"
#    schedule:
#      interval: "daily"

# Our own CI job is responsible for updating this Docker file now.
#  - package-ecosystem: "docker"
#    directory: "/"
#    schedule:
#      interval: "daily"

# Our own CI job is responsible for updating this Docker file now.
#  - package-ecosystem: "docker"
#    directory: "/hack"  # this should keep the FIPS dockerfile updated per https://github.com/dependabot/feedback/issues/145#issuecomment-414738498
#    schedule:
#      interval: "daily"
