[[redirects]]
  from = "/community"
  to = "https://pinniped.dev/community"
  status = 302
  force = true

[[redirects]]
  from = "/community/zoom"
  to = "https://vmware.zoom.us/j/TodoUpdateThisLink"
  status = 302
  force = true

[[redirects]]
  from = "/community/agenda"
  to = "https://hackmd.io/rd_kVJhjQfOvfAWzK8A3tQ"
  status = 302
  force = true

[[redirects]]
  from = "/community/slack"
  to = "https://kubernetes.slack.com/messages/pinniped"
  status = 302
  force = true

[[redirects]]
  from = "/community/group"
  to = "https://groups.google.com/forum/#!forum/project-pinniped"
  status = 302
  force = true

[[redirects]]
  from = "/community/youtube"
  to = "https://www.youtube.com/playlist?list=PL7bmigfV0EqQ8qYn8ornuJnuGvCt0belt"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
